import React from 'react';
import { Button, Tag, Input, FilterChip } from '../src/index.jsx';
import { Header } from './shared.jsx';
export default {title:'MDS/Core/Controls'};
export const Buttons={name:'버튼 · 변형과 상태',render:()=> <div><Header title="Button">행동은 또렷하게, 움직임은 절제해서. LDS의 키보드·로딩·비활성 동작을 계승합니다.</Header><div className="ml-control-stack"><div className="ml-specimen-row"><Button>프로젝트 열기</Button><Button variant="outlined" color="assistive">변경 취소</Button><Button variant="signal">실험 실행</Button><Button variant="ghost">닫기</Button></div><div className="ml-specimen-row"><Button size="sm">작게</Button><Button size="md">기본</Button><Button size="lg">크게</Button></div><div className="ml-specimen-row"><Button disabled>사용할 수 없음</Button><Button loading="inline">저장 중</Button><Button loading loadingLabel="실험 준비 중">실험 준비</Button></div><section className="ml-specimen-panel" data-theme="dark"><div className="ml-specimen-row"><Button>프로젝트 열기</Button><Button variant="outlined" color="assistive">변경 취소</Button><Button variant="signal">실험 실행</Button></div></section></div></div>};
function ChipDemo(){const[selected,setSelected]=React.useState('전체');return <div><Header title="Tag & filter">읽는 태그와 선택하는 필터를 구분합니다. 필터의 선택 상태는 키보드와 스크린 리더에도 전달됩니다.</Header><div className="ml-specimen-row"><Tag tone="neutral" size="md">Physical AI</Tag><Tag tone="neutral" size="md">로봇 학습</Tag><Tag tone="neutral" size="md">산업용 로봇</Tag></div><h2>분류 필터</h2><div className="ml-specimen-row">{['전체','로보틱스','Physical AI','기업 동향'].map(label=><FilterChip key={label} active={selected===label} onClick={()=>setSelected(label)}>{label}</FilterChip>)}<FilterChip disabled>준비 중</FilterChip></div><p role="status">선택한 분류: {selected}</p></div>}
export const Chips={name:'태그와 필터',render:()=> <ChipDemo/>};
export const Fields={name:'입력 · 기본과 오류',render:()=> <div><Header title="Input">레이블, 보조 설명과 오류 메시지를 함께 제공합니다.</Header><div className="ml-specimen-grid"><Input label="원문 URL" type="url" placeholder="https://" helper="요약의 근거가 된 원문 주소를 입력합니다."/><Input label="원문 URL" type="url" defaultValue="example" error="https://로 시작하는 원문 주소를 입력하세요."/><Input label="출처명" defaultValue="준비 중인 출처" disabled/><Input label="출처명" defaultValue="수정할 수 없는 출처" readOnly/></div></div>};
function InteractionDemo(){const[count,setCount]=React.useState(0);const[busy,setBusy]=React.useState(false);return <div><Header title="Interaction">버튼 활성화와 처리 중 초점 유지. 아래 예시는 외부 데이터를 전송하지 않습니다.</Header><div className="ml-specimen-row"><Button onClick={()=>setCount(x=>x+1)}>횟수 늘리기</Button><Button loading={busy?'inline':false} onClick={()=>setBusy(true)}>저장 예시</Button><Button variant="outlined" color="assistive" onClick={()=>setBusy(false)}>상태 초기화</Button></div><p role="status">활성화 횟수: {count} · {busy?'처리 중':'준비됨'}</p></div>}
export const Interaction={name:'키보드와 로딩',render:()=> <InteractionDemo/>};
