import React,{useState} from 'react';
import {userEvent,within} from 'storybook/test';
import {ProductLockup,Button,Lockup} from '../packages/moment/src/index.jsx';
export default {id:'lds-theme-brand-product-lockup',title:'MDS Theme/Brand/Product Lockup',tags:['autodocs'],component:ProductLockup,parameters:{storyGuide:{storyId:'lds-theme-brand-product-lockup--product-lockup-standard',eyebrow:'Theme / Brand',title:'연구 도구의 이름을 Moment Lab과 함께 표시합니다',description:'Console과 Portal은 구성 예시용 슬롯 이름입니다. 운영 중인 제품의 출시나 승인을 의미하지 않습니다.'},docs:{description:{component:'모먼트랩 마크와 도구 이름을 조합합니다. 접힌 탐색 영역에서는 마크만 표시하고 접근성 이름은 유지합니다.'}}}};
export const ProductLockupStandard={name:'개요',render:()=> <div style={{display:'grid',gap:'var(--space-5)',width:'min(760px, 100%)',fontFamily:'var(--font-sans)'}}>
 <section style={{display:'grid',gap:'var(--space-3)'}}><strong>제품 이름 구성 예시 · full</strong><div style={{display:'flex',flexWrap:'wrap',alignItems:'center',gap:'var(--space-6)',padding:'var(--space-4)',border:'1px solid var(--color-semantic-line-normal-normal)',borderRadius:'var(--radius-lg)',background:'var(--color-semantic-background-elevated-normal)'}}><ProductLockup product="console" height={20}/><ProductLockup product="portal" height={20}/></div></section>
 <section style={{display:'grid',gap:'var(--space-3)'}}><strong>Portal · Lockup / ProductLockup</strong><div style={{display:'grid',gridTemplateColumns:'minmax(100px, auto) 1fr',alignItems:'center',columnGap:'var(--space-4)',rowGap:'var(--space-3)',padding:'var(--space-4)',border:'1px solid var(--color-semantic-line-normal-normal)',borderRadius:'var(--radius-lg)'}}><span>Lockup</span><Lockup variant="portal" height={20}/><span>ProductLockup</span><ProductLockup product="portal" height={20}/></div><p>한 줄형과 도구 이름 분리형을 비교합니다. 두 조합의 동일 geometry를 보장하는 정본 관계는 아닙니다.</p></section>
 <section style={{display:'grid',gap:'var(--space-3)'}}><strong>브랜드 배경 · reverse</strong><div data-theme="dark" style={{padding:'var(--space-4)',borderRadius:'var(--radius-lg)',background:'var(--color-semantic-brand-surface)'}}><ProductLockup product="console" appearance="reverse" height={20}/></div></section>
 <section style={{display:'grid',gap:'var(--space-3)'}}><strong>접힌 rail · compact / 홈 링크</strong><div style={{display:'flex',alignItems:'center',gap:'var(--space-6)'}}><ProductLockup product="console" compact height={20}/><a href="#research" aria-label="연구 도구 홈"><ProductLockup product="console" decorative height={20}/></a></div></section>
 </div>,play:async({canvasElement})=>{const portalText=canvasElement.querySelector('[data-lockup-variant="portal"] text');if(portalText.getBBox().x+portalText.getBBox().width>portalText.ownerSVGElement.viewBox.baseVal.width)throw Error('Portal wordmark is clipped');const images=canvasElement.querySelectorAll('[data-product-lockup-mode]');if(images.length!==6)throw Error('Product lockup variants missing');if(images[0].getAttribute('aria-label')!=='Moment Lab Console')throw Error('Product identity missing');if(images[4].querySelector('text'))throw Error('Compact mode must show the mark alone');if(images[5].getAttribute('aria-hidden')!=='true')throw Error('Linked logo must be decorative');}};
function Reveal(){const[compact,setCompact]=useState(true);return <main style={{display:'grid',gap:'var(--space-5)',maxWidth:320}}><ProductLockup product="console" compact={compact}/><Button onClick={()=>setCompact(v=>!v)}>{compact?'제품 이름 펼치기':'제품 이름 접기'}</Button></main>}
export const NarrowCompact={name:'반응형 · 접힌 탐색 영역',render:()=> <Reveal/>,play:async({canvasElement})=>{await userEvent.click(within(canvasElement).getByRole('button'));if(!canvasElement.querySelector('[data-product-lockup-mode="full"]'))throw Error('Product name must expand');await userEvent.click(within(canvasElement).getByRole('button'));if(!canvasElement.querySelector('[data-product-lockup-mode="compact"]'))throw Error('Product name must collapse');}};
