import assert from 'node:assert/strict';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..');
const read=p=>readFileSync(path.join(root,p),'utf8');
const generation=spawnSync('python3',['scripts/generate-moment-theme.py','--check'],{cwd:root,encoding:'utf8'});
assert.equal(generation.status,0,generation.stdout+generation.stderr);
const contract=JSON.parse(read('packages/core/tokens/semantic-contract.json'));
const cssFiles=[];
const seenCss=new Set();
function reachable(file){ if(seenCss.has(file))return; seenCss.add(file); cssFiles.push(file); for(const m of read(file).matchAll(/@import\s+["']([^"']+)["']/g))reachable(path.posix.normalize(path.posix.join(path.posix.dirname(file),m[1]))); };
reachable('packages/moment/styles.css');
const css=cssFiles.map(read).join('\n');
const declared=new Set([...css.matchAll(/(--[\w-]+)\s*:/g)].map(m=>m[1]));
const missing=contract.requiredVariables.filter(v=>!declared.has(v));
assert.deepEqual(missing,[],`Missing Core theme variables: ${missing}`);
assert(existsSync(path.join(root,'packages/moment/dist/index.js')),'Run build first');
const api=await import('../packages/moment/dist/index.js');
for(const key of ['Button','Input','Card','Chip','Tag','FilterChip','SourceTag','MonoLabel','MomentMark','Lockup','EditorialCard'])assert(api[key],`Missing export ${key}`);
const types=spawnSync(process.execPath,['node_modules/typescript/bin/tsc','-p','tsconfig.moment.json'],{cwd:root,encoding:'utf8'});
assert.equal(types.status,0,types.stdout+types.stderr);
const pkg=JSON.parse(read('packages/moment/package.json'));
assert(!pkg.dependencies,'The Moment package must not need private LDS registry packages');
assert(pkg.private,'Publishing requires a separately prepared release');
const ajv=new Ajv2020({strict:false});
addFormats(ajv);
const validate=ajv.compile(JSON.parse(read('docs/references/adoption/LDS_UI_ADOPTION_REPORT.schema.json')));
assert(validate(JSON.parse(read('docs/moment/adoption-report.json'))),JSON.stringify(validate.errors));
console.log(`Moment checks passed: ${contract.requiredVariables.length} Core theme requirements, ${Object.keys(api).length} exports, portable consumer types.`);
