import assert from 'node:assert/strict';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..');
const read=p=>readFileSync(path.join(root,p),'utf8');
const generation=spawnSync('python3',['scripts/generate-moment-theme.py','--check'],{cwd:root,encoding:'utf8'});
assert.equal(generation.status,0,generation.stdout+generation.stderr);
const contracts=['core','product'].map(layer=>JSON.parse(read(`packages/${layer}/tokens/semantic-contract.json`)));
const contract={requiredVariables:[...new Set(contracts.flatMap(c=>c.requiredVariables))]};
const cssFiles=[];
const seenCss=new Set();
function reachable(file){ if(seenCss.has(file))return; seenCss.add(file); cssFiles.push(file); for(const m of read(file).matchAll(/@import\s+["']([^"']+)["']/g))reachable(path.posix.normalize(path.posix.join(path.posix.dirname(file),m[1]))); };
reachable('packages/moment/styles.css');
const css=cssFiles.map(read).join('\n');
assert(read('packages/moment/tokens/fonts.css').includes('../inherited/theme/tokens/fonts.css'), 'MDS must use the original LDS font provider');
assert(!/--font-(?:sans|mono|brand)\s*:/.test(read('packages/moment/tokens/theme.css')), 'The brand theme must not replace inherited font stacks');
assert(!read('packages/moment/tokens/components.css').includes('data-ml-expression'), 'No separate editorial geometry');
const declared=new Set([...css.matchAll(/(--[\w-]+)\s*:/g)].map(m=>m[1]));
const missing=contract.requiredVariables.filter(v=>!declared.has(v));
assert.deepEqual(missing,[],`Missing Core theme variables: ${missing}`);
assert(existsSync(path.join(root,'packages/moment/dist/index.js')),'Run build first');
const api=await import('../packages/moment/dist/index.js');
for(const key of ['Button','Input','Card','Chip','Tag','FilterChip','SourceTag','MonoLabel','MomentMark','Lockup','MomentLockup','MomentSourceTag','LdsProvider','MdsProvider','DataGrid','DashboardShell','Map2DCanvas','EditorialCard'])assert(api[key],`Missing export ${key}`);
const types=spawnSync(process.execPath,['node_modules/typescript/bin/tsc','-p','tsconfig.moment.json'],{cwd:root,encoding:'utf8'});
assert.equal(types.status,0,types.stdout+types.stderr);
const pkg=JSON.parse(read('packages/moment/package.json'));
assert(!Object.keys(pkg.dependencies||{}).some(name=>name.startsWith('@lk-')), 'No private LDS registry dependency may escape the aggregate package');
assert(pkg.private,'Publishing requires a separately prepared release');
const ajv=new Ajv2020({strict:false});
addFormats(ajv);
const validate=ajv.compile(JSON.parse(read('docs/references/adoption/LDS_UI_ADOPTION_REPORT.schema.json')));
assert(validate(JSON.parse(read('docs/moment/adoption-report.json'))),JSON.stringify(validate.errors));
console.log(`Moment checks passed: ${contract.requiredVariables.length} Core/Product theme requirements, ${Object.keys(api).length} exports, portable consumer types.`);
